"""
Trains the RiskClassifier on synthetic patient data generated by
data/synthetic/generate_patients.py.

Usage:
    python models/train.py --epochs 30
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset, random_split

from models.features import featurize, feature_dim, RISK_LABEL_TO_IDX
from models.risk_classifier import RiskClassifier

DATA_PATH = Path(__file__).parent.parent / "data" / "synthetic" / "patients.csv"
CHECKPOINT_DIR = Path(__file__).parent / "checkpoints"


class PatientDataset(Dataset):
    def __init__(self, rows: list[dict]):
        self.rows = rows

    def __len__(self):
        return len(self.rows)

    def __getitem__(self, idx):
        row = self.rows[idx]
        x = featurize(int(row["age"]), int(row["duration_hours"]), row["symptom_text"])
        y = torch.tensor(RISK_LABEL_TO_IDX[row["risk_label"]], dtype=torch.long)
        return x, y


def load_rows() -> list[dict]:
    if not DATA_PATH.exists():
        raise FileNotFoundError(
            f"{DATA_PATH} not found. Run "
            "`python data/synthetic/generate_patients.py` first."
        )
    with open(DATA_PATH) as f:
        return list(csv.DictReader(f))


def train(epochs: int = 30, batch_size: int = 32, lr: float = 1e-3):
    rows = load_rows()
    dataset = PatientDataset(rows)

    val_size = max(1, int(0.15 * len(dataset)))
    train_size = len(dataset) - val_size
    train_ds, val_ds = random_split(dataset, [train_size, val_size])

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=batch_size)

    model = RiskClassifier(input_dim=feature_dim())
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    best_val_acc = 0.0
    CHECKPOINT_DIR.mkdir(exist_ok=True)

    for epoch in range(1, epochs + 1):
        model.train()
        total_loss = 0.0
        for x, y in train_loader:
            optimizer.zero_grad()
            logits = model(x)
            loss = criterion(logits, y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item() * x.size(0)

        train_loss = total_loss / len(train_ds)
        val_acc = evaluate(model, val_loader)

        print(f"Epoch {epoch:02d} | train_loss={train_loss:.4f} | val_acc={val_acc:.3f}")

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            torch.save(model.state_dict(), CHECKPOINT_DIR / "risk_classifier.pt")

    print(f"Best val accuracy: {best_val_acc:.3f}")
    print(f"Saved best checkpoint to {CHECKPOINT_DIR / 'risk_classifier.pt'}")


@torch.no_grad()
def evaluate(model: RiskClassifier, loader: DataLoader) -> float:
    model.eval()
    correct = 0
    total = 0
    for x, y in loader:
        logits = model(x)
        preds = torch.argmax(logits, dim=-1)
        correct += (preds == y).sum().item()
        total += y.size(0)
    return correct / total if total else 0.0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--lr", type=float, default=1e-3)
    args = parser.parse_args()

    train(epochs=args.epochs, batch_size=args.batch_size, lr=args.lr)
